export const GLOBAL_EVENTS = {
  CHANGE_STORE: 'CHANGE_STORE',
  CHANGE_LOCALE: 'CHANGE_LOCALE',
  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_THEME_DARK: 'CHANGE_THEME_DARK',
  CHANGE_THEME_LIGHT: 'CHANGE_THEME_LIGHT',
  CHANGE_THEME_SYSTEM: 'CHANGE_THEME_SYSTEM',
  REFRESH_LIST: 'REFRESH_LIST',
};

export const ORDER_EVENTS = {
  PREVIEW_IMAGE: 'PREVIEW_IMAGE',
};
export const STRIPE_EVENTS = {
  INITIAL_STRIPE: 'INITIAL_STRIPE',
  SUBMIT_CREDIT_CARD: 'SUBMIT_CREDIT_CARD',
  ADD_NEW_PAYMENT_METHOD: 'ADD_NEW_PAYMENT_METHOD',
  REFRESH_AUTO_REFILL: 'REFRESH_AUTO_REFILL'
};
